- hosts: all
  become: true
  gather_facts: yes
       
  roles:
    - role: geerlingguy.pip

  tasks:
    - name: Creates app directory
      ansible.builtin.file:
        path: "{{ app_path }}"
        state: directory
      tags: redmine      

    - name: Copy .env
      ansible.builtin.template:
        src: templates/.env.template
        dest: "{{ app_path }}/.env"
      tags: redmine

    - name: Run redmine container    
      community.docker.docker_container:
        name: app
        image: redmine:latest
        restart_policy: always
        state: started
        ports:
          - "{{ redmine_external_port }}:3000"
        env_file: "{{ app_path }}/.env"
      tags: redmine
  
- hosts: webservers
  become: true
  gather_facts: yes

  roles: 
    - role: datadog.datadog
      tags: datadog