- hosts: all
  become: true
  gather_facts: yes

  vars:
    pip_install_packages:
      - name: docker  
           
  roles:
    - role: geerlingguy.pip

  tasks:
    - name: Creates app directory
      ansible.builtin.file:
        path: "{{ app_path }}"
        state: directory
        
    - name: Copy .env
      ansible.builtin.template:
        src: .env.template
        dest: "{{ app_path }}/.env"

    - name: Run redmine container    
      community.docker.docker_container:
        name: app
        image: redmine:latest
        restart_policy: always
        state: started
        ports:
          - 3000:3000
        env:
          REDMINE_DB_PASSWORD: "{{ secret_db_password }}"
        env_file: "{{ app_path }}/.env"
  
- hosts: webservers
  become: true
  gather_facts: yes
  vars:
    datadog_api_key: "{{ secret_datadog_key }}"

  roles: 
    - role: datadog.datadog

  tasks:
    - name: Creates datadog directory
      ansible.builtin.file:
        path: /etc/datadog-agent/conf.d/http_check.d
        state: directory
        owner: dd-agent

    - name: Copy http health check config
      ansible.builtin.copy:
        src: services/datadog/http_check.yaml
        dest: /etc/datadog-agent/conf.d/http_check.d/http_check.yaml
        owner: dd-agent
      notify: Restart Datadog

  handlers:
    - name: Restart Datadog
      ansible.builtin.service: 
        name: datadog-agent 
        state: restarted