- hosts: all
  become: true
  gather_facts: no

  vars:
    datadog_api_key: "a7a5f94d9e8b550ae76295f742d534ae"
    datadog_site: "datadoghq.eu"
    app_path: ~/app
    pip_install_packages:
      - name: docker  

  pre_tasks:
    - name: Creates directory
      ansible.builtin.file:
        path: /etc/datadog-agent/conf.d
        state: directory

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: services/datadog/http_check.yaml
        dest: /etc/datadog-agent/conf.d/http_check.yaml
        mode: 777

    - name: Install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        
    - name: Add GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker rep
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
            
    - name: Check docker service status
      service:
        name: docker
        state: started
        enabled: yes
      notify: Restart docker
           
  handlers:
    - name: Restart docker
      service: 
        name: docker 
        state: restarted

  roles:
    - geerlingguy.pip
    - datadog.datadog

  tasks:
    - name: Creates directory
      file:
        path: "{{ app_path }}"
        state: directory

    - name: Copy environment variable
      ansible.builtin.copy:
        src: .env
        dest: "{{ app_path }}/.env"

    - name: Run redmine container    
      community.docker.docker_container:
        name: app
        image: redmine:latest
        restart_policy: always
        state: started
        ports:
          - 3000:3000
        env:
          REDMINE_DB_PASSWORD: "{{ DB_PASSWORD }}"
        env_file: "{{ app_path }}/.env"
  