- hosts: all
  become: true
  gather_facts: no

  vars:
    pip_install_packages:
      - name: docker  

  roles:
    - geerlingguy.pip

  tasks:
    - community.docker.docker_container:
        name: app
        image: redmine:latest
        restart_policy: always
        state: started
        ports:
          - 3000:3000
        env_file: .env
  