- hosts: all
  become: true
  gather_facts: no
  pre_tasks:
    - name: Install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        
    - name: Add GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker rep
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
            
    - name: Check docker service status
      service:
        name: docker
        state: started
        enabled: yes
      notify: Restart docker
           
  handlers:
    - name: Restart docker
      service: 
        name: docker 
        state: restarted

  vars:
    pip_install_packages:
      - name: docker  

  roles:
    - geerlingguy.pip

  tasks:
    - community.docker.docker_container:
        name: app
        image: redmine:latest
        restart_policy: always
        state: started
        ports:
          - 3000:3000
        env_file: .env
  